version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_DB=n8n_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - poc_network

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_db
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password123
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./simulated_data:/data_input
    depends_on:
      - postgres
    networks:
      - poc_network

  dashboard:
    image: python:3.9-slim
    working_dir: /app
    ports:
      - "8501:8501"  # <--- ¡ESTO ES LO NUEVO!
    volumes:
      - ./dashboard:/app
    command: tail -f /dev/null
    networks:
      - poc_network

networks:
  poc_network:
